# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='img_url',
            field=models.CharField(max_length=300),
        ),
    ]
